services:
  backend:
    build: .
    command:
      [
        "/app/wait_for_db.sh",
        "db",
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - BACKEND_CORS_ORIGINS=["https://resmatchai.com", "https://res-match-ui.vercel.app", "http://localhost:3000"]
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=res_match

  db:
    image: pgvector/pgvector:pg15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: res_match
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
