"""Add feature

Revision ID: 02d6a12bf373
Revises: 49e5c8ae6296
Create Date: 2025-06-25 14:48:20.095834

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "02d6a12bf373"
down_revision: Union[str, None] = "49e5c8ae6296"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("resumes", sa.Column("file_name", sa.String(), nullable=False))
    op.add_column("resumes", sa.Column("extracted_text", sa.Text(), nullable=True))
    op.add_column("resumes", sa.Column("llm_feedback", sa.Text(), nullable=True))
    op.alter_column(
        "resumes", "upload_date", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.drop_column("resumes", "embedding")
    op.drop_column("resumes", "filename")
    op.drop_column("resumes", "content")
    op.drop_column("resumes", "feedback")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resumes", sa.Column("feedback", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "resumes", sa.Column("content", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "resumes",
        sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "resumes",
        sa.Column("embedding", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "resumes", "upload_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_column("resumes", "llm_feedback")
    op.drop_column("resumes", "extracted_text")
    op.drop_column("resumes", "file_name")
    # ### end Alembic commands ###
