"""Switch username to email in user model

Revision ID: 04bb6629dd6f
Revises: 7c2a98416a59
Create Date: 2025-06-14 19:56:06.830237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04bb6629dd6f"
down_revision: Union[str, None] = "7c2a98416a59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(), nullable=False))
    op.drop_index("ix_users_username", table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index("ix_users_username", "users", ["username"], unique=True)
    op.drop_column("users", "email")
    # ### end Alembic commands ###
