"""Add firstname and lastname fields to users table

Revision ID: 2320a081c663
Revises: d9145575d29c
Create Date: 2025-08-05 16:14:15.619431

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "2320a081c663"
down_revision: Union[str, None] = "d9145575d29c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "firstname",
            sa.String(),
            server_default=sa.text("'Unknown'"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "lastname", sa.String(), server_default=sa.text("'User'"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "lastname")
    op.drop_column("users", "firstname")
    # ### end Alembic commands ###
