"""Add feature

Revision ID: 49e5c8ae6296
Revises: 1de75f248ee9
Create Date: 2025-06-25 13:54:49.360798

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "49e5c8ae6296"
down_revision: Union[str, None] = "1de75f248ee9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "resumes", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "resumes", type_="unique")
    # ### end Alembic commands ###
