"""add_oauth_fields_to_user

Revision ID: 4a4bce243185
Revises: 2320a081c663
Create Date: 2025-08-22 16:25:47.850370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4a4bce243185'
down_revision: Union[str, None] = '2320a081c663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('provider', sa.String(), server_default=sa.text("'email'"), nullable=False))
    op.add_column('users', sa.Column('is_oauth', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'is_oauth')
    op.drop_column('users', 'provider')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
