"""Add firstname and lastname to users table

Revision ID: a1b2c3d4e5f6
Revises: 76c3e9f92704
Create Date: 2025-01-09 10:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = "76c3e9f92704"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("firstname", sa.String(), nullable=False))
    op.add_column("users", sa.Column("lastname", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "lastname")
    op.drop_column("users", "firstname")
    # ### end Alembic commands ###
