name: Checks

on: [push]

jobs:
  test-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose version

      - name: Test
        run: docker compose run --rm backend sh -c "pytest"

      - name: Check formatting with Black
        run: docker compose run --rm backend sh -c "black --check ."
