name: Checks

on: [push]

jobs:
  test-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose version

      - name: Test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          TESTING: true
        run: docker compose run --rm -e SECRET_KEY -e ALGORITHM -e GOOGLE_CLIENT_ID -e GOOGLE_CLIENT_SECRET -e TESTING backend sh -c "pytest"

      - name: Check formatting with Black
        run: docker compose run --rm backend sh -c "black --check ."
